### ISSUE TITLE
request for being able to add opacity

### ISSUE THREAD

**Issue by kristus123** [RSG-Group/hyper-background#22] opened 2023-10-06 11:59 UTC
It would be nice to be able to turn the opacity down/up

**Comment by retrixe** [comment] 2023-10-14 12:13
Duplicate of #5

I haven't been using Hyper in years now but I will still get Hyper and try to look at this request as well as your bug report in some time
It seems Hyper v4 is around the horizon so I will try to look into making sure the plugin is compatible there as well

**Closed as completed by retrixe** 2023-10-14 12:13 UTC
Labels: duplicate, enhancement
